### ISSUE TITLE
怎么画posterior图像

### ISSUE THREAD

**Issue by gw150914** [yi-fan-wang/whugwnotes#1]
王师兄你好，我是武大的博士生袁泳，我有点不懂的问题想请教下你。通过pycbc_inference，我跑了下pycbc 中 GW150914的例子(http://pycbc.org/pycbc/latest/html/inference/examples/gw150914.html), 得到后验参数的结果，结果保存在hdf文件里，但是我在pycbc上查了下，按照他的例子，我没有画出后验分布的corner图像来。所以想请教下怎么通过hdf文件画后验分布的corner图。

**Comment by yi-fan-wang** [comment]
@gw150914 （用issues交流非常赞！）

参数估计的结果保存在hdf文件中`f['samples']['参数的名字'][:]`中，你可以选取其中一维来分析它的分布、中位数、置信区间，也可选取任意两维用KDE画出它们的二维后验分布。至于画图，可以采用`pycbc`中的现成工具`pycbc_plot_inference_posterior`来做，具体的方法可参考该工具的文档（运行该命令+`help`）。一个例子为：

> pycbc_inference_plot_posterior \
>        --plot-contours  \
>        --plot-marginal  \
>       --plot-scatter \
>       --z-arg snr \
>       --input-file  一个文件.hdf \
>       --output-file 一个图片.png \
>       --parameters 一些参数，比如"mass1 mass2"等等

**Comment by gw150914** [comment]
非常感谢王师兄，根据你提供的code，我成功的画出了posterior的图像。
想加师兄的微信不知道可不可以。
我的微信号是yuan1450700001




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yi-fan-wang/whugwnotes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 晚上11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yi-fan-wang/whugwnotes] 怎么画posterior图像 (Issue #1)





 
@gw150914 （用issues交流非常赞！）
 
参数估计的结果保存在hdf文件中f['samples']['参数的名字'][:]中，你可以选取其中一维来分析它的分布、中位数、置信区间，也可选取任意两维用KDE画出它们的二维后验分布。至于画图，可以采用pycbc中的现成工具pycbc_plot_inference_posterior来做，具体的方法可参考该工具的文档（运行该命令+help）。一个例子为：
  
pycbc_inference_plot_posterior 
 --plot-contours  
 --plot-marginal  
 --plot-scatter 
 --z-arg snr 
 --input-file  一个文件.hdf 
 --output-file 一个图片.png 
 --parameters 一些参数，比如"mass1 mass2"等等
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
